#官方source
source 'https://github.com/CocoaPods/Specs.git'
#私有source
source 'https://git.coding.net/zjqx/RevanSpecs.git'


use_frameworks!

target 'RevanMainModule_Example' do
  pod 'RevanMainModule', :path => '../'

  target 'RevanMainModule_Tests' do
    inherit! :search_paths

    
  end
end
